"""
Dynamic tool registry — allows the agent to create and register new tools at runtime.

Tools are saved as Python modules in the workspace/tools/ directory.
On startup, all saved tools are loaded and their definitions + implementations
are registered in the global TOOL_DEFINITIONS and TOOL_IMPLS dictionaries.
"""

import os
import json
import importlib
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import Any

# Directory where dynamic tool scripts are saved
WORKSPACE = Path(os.environ.get("ESAPIENS_DATA_DIR", os.path.expanduser("~/esapiens-data")))
DYNAMIC_TOOLS_DIR = WORKSPACE / "tools"
DYNAMIC_TOOLS_DIR.mkdir(parents=True, exist_ok=True)

# Registry file: maps tool_name -> {module_path, definition, created_at}
_REGISTRY_PATH = DYNAMIC_TOOLS_DIR / "_registry.json"


def _load_registry() -> dict:
    """Load the tool registry from disk."""
    if _REGISTRY_PATH.exists():
        with open(_REGISTRY_PATH) as f:
            return json.load(f)
    return {"tools": {}}


def _save_registry(registry: dict) -> None:
    """Save the tool registry to disk."""
    with open(_REGISTRY_PATH, "w") as f:
        json.dump(registry, f, indent=2)


def create_tool(
    name: str,
    description: str,
    parameters: dict,
    code: str,
) -> dict:
    """
    Create a new dynamic tool and register it for use by the agent.

    Args:
        name: Tool name (lowercase, underscores allowed, e.g. 'download_geo')
        description: Human-readable description of what the tool does
        parameters: JSON schema dict for parameters, e.g.
            {
                "type": "object",
                "properties": {
                    "geo_id": {"type": "string", "description": "GEO accession (e.g. GSE12345)"}
                },
                "required": ["geo_id"]
            }
        code: Python function body. The function receives parameters as kwargs.
               Must return a dict (JSON-serializable). Available imports: os, json, httpx,
               subprocess, sys, tempfile, base64, io, textwrap, Path.

    Returns:
        dict with status and tool info
    """
    # Validate name
    if not name.replace("_", "").isalnum():
        return {"error": f"Invalid tool name: {name}. Use lowercase letters, numbers, underscores."}

    # Sanitize name
    safe_name = name.lower().strip().replace("-", "_").replace(" ", "_")

    # Build the parameter list from the schema
    param_props = parameters.get("properties", {})
    required = parameters.get("required", [])
    param_list = []
    for pname, pdef in param_props.items():
        default_val = pdef.get("default")
        if pname in required:
            if default_val is not None:
                param_list.append(f"{pname}={repr(default_val)}")
            else:
                param_list.append(pname)
        else:
            if default_val is not None:
                param_list.append(f"{pname}={repr(default_val)}")
            else:
                param_list.append(f"{pname}=None")

    params_sig = ", ".join(param_list)

    # Build the full Python module
    module_code = textwrap.dedent(f"""\
\"\"\"Dynamic tool: {safe_name}

Auto-generated by E.sapiens agent.
Description: {description}
\"\"\"

import os
import json
import httpx
import subprocess
import sys
import tempfile
import base64
import io
import textwrap
from pathlib import Path

WORKSPACE = Path(os.environ.get("ESAPIENS_DATA_DIR", os.path.expanduser("~/esapiens-data")))


def {safe_name}({params_sig}{', ' if params_sig else ''}**kwargs):
    \"\"\"{description}\"\"\"
{textwrap.indent(textwrap.dedent(code), "    ")}
""")

    # Write module file
    module_path = DYNAMIC_TOOLS_DIR / f"tool_{safe_name}.py"
    module_path.write_text(module_code)

    # Test import to verify syntax
    try:
        spec = importlib.util.spec_from_file_location(
            f"dynamic_tool_{safe_name}", str(module_path)
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        func = getattr(mod, safe_name)
    except Exception as e:
        # Remove broken module
        module_path.unlink(missing_ok=True)
        return {"error": f"Tool code failed to load: {e}"}

    # Register in TOOL_DEFINITIONS and TOOL_IMPLS
    definition = {
        "name": safe_name,
        "description": description,
        "parameters": parameters,
    }
    # Import the tools module to register
    from tools import TOOL_DEFINITIONS, TOOL_IMPLS

    # Remove old definition if exists
    TOOL_DEFINITIONS[:] = [t for t in TOOL_DEFINITIONS if t["name"] != safe_name]
    TOOL_DEFINITIONS.append(definition)
    TOOL_IMPLS[safe_name] = func

    # Save to registry
    registry = _load_registry()
    registry["tools"][safe_name] = {
        "module_path": str(module_path),
        "definition": definition,
    }
    _save_registry(registry)

    return {
        "status": "created",
        "tool": safe_name,
        "description": description,
        "parameters": list(param_props.keys()),
        "message": f"Tool '{safe_name}' created and registered. It is now available for use.",
    }


def load_dynamic_tools() -> list[dict]:
    """
    Load all previously created dynamic tools from the registry.
    Returns list of definitions that were loaded.
    """
    from tools import TOOL_DEFINITIONS, TOOL_IMPLS

    registry = _load_registry()
    loaded = []

    for tool_name, info in registry.get("tools", {}).items():
        module_path = Path(info["module_path"])
        if not module_path.exists():
            continue

        try:
            spec = importlib.util.spec_from_file_location(
                f"dynamic_tool_{tool_name}", str(module_path)
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            func = getattr(mod, tool_name)
        except Exception as e:
            print(f"[DynamicTools] Failed to load {tool_name}: {e}")
            continue

        definition = info["definition"]
        # Remove old if exists
        TOOL_DEFINITIONS[:] = [t for t in TOOL_DEFINITIONS if t["name"] != tool_name]
        TOOL_DEFINITIONS.append(definition)
        TOOL_IMPLS[tool_name] = func
        loaded.append(definition)

    if loaded:
        print(f"[DynamicTools] Loaded {len(loaded)} dynamic tools: {[t['name'] for t in loaded]}")

    return loaded