"""
E.sapiens PDF Report Generator
══════════════════════════════════════════════════════════════════

Generates professional PDF reports from session conversations using fpdf2.
Styled to match the Hard Tech Noir aesthetic --  clean, monospaced, technical.

Usage:
    from report import generate_session_report
    pdf_bytes = generate_session_report(session_data)
"""

import re
from datetime import datetime, timezone
from typing import Any, Optional

from fpdf import FPDF


# ═══════════════════════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════════════════════

# Accent colors (matches frontend palette)
C_PRIMARY = (7, 7, 11)  # #07070B --  deep midnight
C_ACCENT_BLUE = (0, 191, 255)  # #00BFFF --  electric blue
C_ACCENT_CYAN = (0, 245, 255)  # #00F5FF --  neon cyan
C_ACCENT_GREEN = (0, 255, 136)  # #00FF88
C_ACCENT_AMBER = (255, 184, 0)  # #FFB800
C_ACCENT_RED = (255, 51, 85)  # #FF3355
C_TEXT_PRIMARY = (232, 232, 240)  # #E8E8F0
C_TEXT_SECONDARY = (136, 136, 160)  # #8888A0
C_TEXT_DIMMED = (85, 85, 112)  # #555570
C_BG_CARD = (18, 18, 30)  # #12121E
C_BG_SURFACE = (11, 11, 16)  # #0B0B10
C_BORDER = (26, 26, 46)  # #1A1A2E
C_WHITE = (255, 255, 255)
C_BLACK = (0, 0, 0)
C_LIGHT_GRAY = (240, 240, 245)


# ═══════════════════════════════════════════════════════════════════════════
# Custom PDF class
# ═══════════════════════════════════════════════════════════════════════════


class ReportPDF(FPDF):
    """Custom PDF with E.sapiens branding and Hard Tech Noir styling."""

    def __init__(self) -> None:
        super().__init__("P", "mm", "A4")
        self.set_auto_page_break(auto=True, margin=20)

        # Register monospace font
        # Search common monospace font paths
        mono_font_path = self._find_mono_font()
        if mono_font_path:
            self.add_font("JetBrainsMono", "", mono_font_path, uni=True)
            self.add_font("JetBrainsMono", "B", mono_font_path, uni=True)
            self._mono_available = True
        else:
            self._mono_available = False

    def _find_mono_font(self) -> Optional[str]:
        """Find a monospace font file on the system."""
        import os

        candidates = [
            # macOS
            "/System/Library/Fonts/Supplemental/Courier New.ttf",
            "/Library/Fonts/Courier New.ttf",
            # Linux
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
            "/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf",
            # Docker (python:3.12-slim may have these)
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        ]
        for path in candidates:
            if os.path.exists(path):
                return path
        return None

    def header(self) -> None:
        """Render page header with E.sapiens branding."""
        if self.page_no() <= 1:
            return
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*C_ACCENT_BLUE)
        self.cell(0, 5, "E.SAPIENS --  Session Report", align="L")
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*C_TEXT_DIMMED)
        self.cell(
            0, 5, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT"
        )
        self.set_draw_color(*C_BORDER)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self) -> None:
        """Render page footer."""
        self.set_y(-15)
        self.set_font("Helvetica", "", 6)
        self.set_text_color(*C_TEXT_DIMMED)
        self.cell(
            0,
            10,
            f"Generated by E.sapiens v2 --  {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
            align="C",
        )


# ═══════════════════════════════════════════════════════════════════════════
# Report Generation
# ═══════════════════════════════════════════════════════════════════════════


def generate_session_report(session: dict[str, Any]) -> bytes:
    """
    Generate a PDF report from a session dict (as returned by StorageBackend.get_session).

    Returns the PDF as raw bytes.
    """
    pdf = ReportPDF()
    messages = session.get("messages", [])
    session_title = _sanitize(session.get("title", "Untitled Session"))
    session_id = _sanitize(session.get("id", "unknown"))
    created = session.get("created_at", "")

    # ═══ Cover Page ═══════════════════════════════════════════════════════════

    pdf.add_page()

    # Header accent bar
    pdf.set_fill_color(*C_ACCENT_BLUE)
    pdf.rect(10, 10, 190, 2, "F")

    # Logo area
    pdf.ln(30)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*C_BLACK)
    pdf.cell(0, 15, "E.SAPIENS", ln=True, align="C")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*C_TEXT_DIMMED)
    pdf.cell(0, 6, "BIOINFORMATICS AGENT --  SESSION REPORT", ln=True, align="C")

    pdf.ln(15)

    # Decorative line
    pdf.set_draw_color(*C_ACCENT_CYAN)
    pdf.set_line_width(0.3)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(10)

    # Session metadata card
    meta_x = 35
    meta_w = 140
    pdf.set_fill_color(*C_BG_CARD)
    pdf.set_draw_color(*C_BORDER)
    pdf.rect(meta_x, pdf.get_y(), meta_w, 50, "DF")
    y_start = pdf.get_y() + 5

    pdf.set_xy(meta_x + 8, y_start)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*C_ACCENT_BLUE)
    pdf.cell(0, 6, "SESSION INFORMATION", ln=True)

    pdf.set_x(meta_x + 8)
    pdf.set_font("Courier", "", 8)
    pdf.set_text_color(*C_TEXT_SECONDARY)
    pdf.cell(60, 5, "Title:", align="L")
    pdf.set_text_color(*C_BLACK)
    pdf.cell(0, 5, session_title, ln=True)

    pdf.set_x(meta_x + 8)
    pdf.set_font("Courier", "", 8)
    pdf.set_text_color(*C_TEXT_SECONDARY)
    pdf.cell(60, 5, "Session ID:", align="L")
    pdf.set_text_color(*C_BLACK)
    pdf.cell(0, 5, session_id, ln=True)

    pdf.set_x(meta_x + 8)
    pdf.set_font("Courier", "", 8)
    pdf.set_text_color(*C_TEXT_SECONDARY)
    pdf.cell(60, 5, "Created:", align="L")
    pdf.set_text_color(*C_BLACK)
    # Parse ISO timestamp for display
    try:
        dt = datetime.fromisoformat(created.replace("Z", "+00:00"))
        created_display = dt.strftime("%Y-%m-%d %H:%M UTC")
    except (ValueError, AttributeError):
        created_display = str(created)
    pdf.cell(0, 5, created_display, ln=True)

    pdf.set_x(meta_x + 8)
    pdf.set_font("Courier", "", 8)
    pdf.set_text_color(*C_TEXT_SECONDARY)
    pdf.cell(60, 5, "Messages:", align="L")
    pdf.set_text_color(*C_BLACK)
    pdf.cell(0, 5, str(len(messages)), ln=True)

    pdf.ln(10)

    # Accent bar at bottom
    pdf.set_fill_color(*C_ACCENT_CYAN)
    pdf.rect(10, 287, 190, 1, "F")

    # ═══ Conversation Pages ═══════════════════════════════════════════════════

    pdf.add_page()

    # Page header
    pdf.set_fill_color(*C_ACCENT_BLUE)
    pdf.rect(10, 10, 190, 1.5, "F")
    pdf.ln(8)

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*C_BLACK)
    pdf.cell(0, 10, "Session Transcript", ln=True)

    pdf.set_draw_color(*C_BORDER)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # Render each message
    msg_count = len(messages)
    for idx, msg in enumerate(messages):
        role = msg.get("role", "unknown")
        content = msg.get("content", "") or ""
        ts = msg.get("timestamp", 0)
        skills = msg.get("skills", [])

        # Skip empty messages
        if not content.strip():
            continue

        # Format timestamp
        if isinstance(ts, (int, float)) and ts > 1000000000000:
            # Milliseconds ->  seconds
            ts_s = ts / 1000
        else:
            ts_s = ts
        try:
            ts_dt = datetime.fromtimestamp(ts_s, tz=timezone.utc)
            ts_str = ts_dt.strftime("%H:%M:%S")
        except (ValueError, OSError, OverflowError):
            ts_str = ""

        # Message header --  role label + timestamp
        if role == "user":
            label = "USER_INPUT"
            label_color = C_ACCENT_CYAN
            accent_color = C_ACCENT_CYAN
        elif role == "assistant":
            label = "E.SAPIENS"
            label_color = C_ACCENT_BLUE
            accent_color = C_ACCENT_BLUE
        else:
            label = "SYSTEM"
            label_color = C_TEXT_DIMMED
            accent_color = C_BORDER

        label = _sanitize(label)
        ts_str = _sanitize(ts_str)

        # Accent bar on the left
        pdf.set_fill_color(*accent_color)
        pdf.rect(10, pdf.get_y(), 1.5, 8, "F")

        # Role label
        pdf.set_font("Courier", "B", 7)
        pdf.set_text_color(*label_color)
        pdf.cell(5, 4, "", align="L")  # spacer
        pdf.cell(0, 4, f"{label}", ln=True)

        # Timestamp and skills
        pdf.set_font("Courier", "", 6)
        pdf.set_text_color(*C_TEXT_DIMMED)
        pdf.cell(5, 4, "")
        ts_display = f"[{ts_str}]" if ts_str else ""
        skills_display = ""
        if skills:
            skill_str = " | ".join(skills) if isinstance(skills, list) else str(skills)
            skills_display = f" | SKILLS: {skill_str}"
        pdf.cell(0, 4, f"{ts_display}{skills_display}", ln=True)

        pdf.ln(1)

        # Message content
        pdf.set_x(13)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*C_BLACK)

        # Render content with code block formatting
        _render_content(pdf, content)

        pdf.ln(3)

        # Separator between messages (except last)
        if idx < msg_count - 1:
            pdf.set_draw_color(*C_BORDER)
            pdf.set_line_width(0.1)
            pdf.line(15, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)

    # ═══ Summary Page (if enough messages) ════════════════════════════════════

    if msg_count > 0:
        pdf.add_page()
        pdf.set_fill_color(*C_ACCENT_CYAN)
        pdf.rect(10, 10, 190, 1.5, "F")
        pdf.ln(8)

        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(*C_BLACK)
        pdf.cell(0, 10, "Report Summary", ln=True)

        pdf.set_draw_color(*C_BORDER)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(8)

        # Summary stats
        user_count = sum(1 for m in messages if m.get("role") == "user")
        assistant_count = sum(1 for m in messages if m.get("role") == "assistant")
        total_chars = sum(len(m.get("content", "") or "") for m in messages)

        stats = [
            ("Total Messages", str(msg_count)),
            ("User Messages", str(user_count)),
            ("Assistant Responses", str(assistant_count)),
            ("Total Characters", f"{total_chars:,}"),
            ("Report Generated", datetime.now().strftime("%Y-%m-%d %H:%M UTC")),
            ("Generator", "E.sapiens v2 --  Hard Tech Noir"),
        ]

        for label, value in stats:
            pdf.set_font("Courier", "B", 8)
            pdf.set_text_color(*C_TEXT_SECONDARY)
            pdf.cell(60, 7, label + ":", align="R")
            pdf.set_font("Courier", "", 8)
            pdf.set_text_color(*C_BLACK)
            pdf.cell(0, 7, "  " + value, ln=True)

    # ═══ Output ═══════════════════════════════════════════════════════════════

    pdf_bytes = pdf.output()
    if isinstance(pdf_bytes, bytearray):
        pdf_bytes = bytes(pdf_bytes)
    elif isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode("latin-1")
    return pdf_bytes


# ═══════════════════════════════════════════════════════════════════════════
# Content Rendering Helpers
# ═══════════════════════════════════════════════════════════════════════════

# Unicode ->  ASCII replacements for PDF core font compatibility
_UNICODE_REPLACEMENTS = {
    "\u2014": "---",  # em dash
    "\u2013": "--",  # en dash
    "\u2018": "'",  # left single quotation
    "\u2019": "'",  # right single quotation
    "\u201c": '"',  # left double quotation
    "\u201d": '"',  # right double quotation
    "\u2026": "...",  # ellipsis
    "\u2022": "*",  # bullet
    "\u2192": "->",  # arrow
    "\u2190": "<-",  # left arrow
    "\u00b0": " deg",  # degree
    "\u00b1": "+/-",  # plus-minus
    "\u00d7": "x",  # multiplication
    "\u00f7": "/",  # division
    "\u2264": "<=",  # less-than-or-equal
    "\u2265": ">=",  # greater-than-or-equal
    "\u2260": "!=",  # not equal
    "\u03b1": "alpha",  # Greek alpha
    "\u03b2": "beta",  # Greek beta
    "\u03b3": "gamma",  # Greek gamma
    "\u03b4": "delta",  # Greek delta
    "\u03b5": "epsilon",
    "\u03bb": "lambda",
    "\u03c0": "pi",
    "\u03c3": "sigma",
    "\u03c9": "omega",
    "\u212b": "Angstrom",
    "\u00c5": "A",  # Angstrom A
}


def _sanitize(text: str) -> str:
    """Replace Unicode characters with ASCII equivalents for PDF core font compatibility."""
    for char, replacement in _UNICODE_REPLACEMENTS.items():
        text = text.replace(char, replacement)
    # Strip remaining non-latin-1 characters
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _render_content(pdf: FPDF, content: str) -> None:
    """
    Render markdown-like content to the PDF.
    Handles code blocks (```...```), inline code (`...`), paragraphs.
    """
    content = _sanitize(content)
    # Split by code blocks
    parts = re.split(r"(```[\s\S]*?```|`[^`]+`)", content)

    for part in parts:
        if not part.strip():
            continue

        if part.startswith("```"):
            # Code block
            _render_code_block(pdf, part)
        elif part.startswith("`") and part.endswith("`"):
            # Inline code
            code_text = part.strip("`")
            pdf.set_font("Courier", "", 7)
            pdf.set_text_color(*C_ACCENT_BLUE)
            pdf.write(4, code_text)
        else:
            # Regular text --  split into paragraphs
            paragraphs = part.split("\n\n")
            for para in paragraphs:
                para = para.strip()
                if not para:
                    continue
                # Handle inline formatting like **bold**, _italic_, etc.
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*C_BLACK)
                # Simple line-by-line for long text
                pdf.multi_cell(0, 4.5, para, new_x="LMARGIN", new_y="NEXT")
                pdf.set_x(13)


def _render_code_block(pdf: FPDF, block: str) -> None:
    """Render a fenced code block with background and monospace font."""
    # Extract content
    lines = block.strip().split("\n")
    # Remove opening and closing ```
    if lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    # Remove optional language tag from first line
    if lines and not lines[0].startswith(" ") and len(lines[0]) < 30:
        lines = (
            lines[1:]
            if not lines[0].startswith(("def ", "import", "from", "class", "```"))
            else lines
        )

    if not lines:
        return

    code_text = "\n".join(lines)
    code_text = _sanitize(code_text)

    # Code block background
    y_before = pdf.get_y()
    x_before = pdf.get_x()

    # Estimate height
    line_count = len(lines)
    line_height = 3.5
    block_height = line_count * line_height + 4  # padding

    # Check if we need a page break
    if y_before + block_height > 270:
        pdf.add_page()
        y_before = pdf.get_y()

    # Draw background
    pdf.set_fill_color(*C_BG_SURFACE)
    pdf.set_draw_color(*C_BORDER)
    pdf.rect(13, y_before, 185, block_height, "DF")

    # Render code
    pdf.set_xy(16, y_before + 2)
    pdf.set_font("Courier", "", 6.5)
    pdf.set_text_color(*C_ACCENT_GREEN)

    for line in lines:
        pdf.set_x(16)
        pdf.cell(0, line_height, line[:120], ln=True)

    pdf.set_y(y_before + block_height + 2)
